spring:
  application:
    name: command-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: user
    password: pass
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql


logging:
  level:
    root: info
    com.pablords: debug
    org:
      hibernate: ERROR
      springframework:
        orm.jpa: ERROR
        transaction: TRACE
        kafka.transaction: DEBUG

server:
  servlet:
    context-path: /api/v1