spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: user
    password: pass
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql


debezium:
  connector:
    name: inventory-postgres-connector
    config:
      connector.class: io.debezium.connector.postgresql.PostgresConnector
      database.hostname: db-command
      database.port: 5432
      database.user: user
      database.password: pass
      database.dbname: inventory
      database.server.name: postgres-inventory
      plugin.name: pgoutput
      slot.name: outbox_slot
      table.include.list: public.outbox_event
      key.converter: org.apache.kafka.connect.json.JsonConverter
      value.converter: org.apache.kafka.connect.storage.StringConverter
      value.converter.schemas.enable: false
      key.converter.schemas.enable: false
      transforms: outbox
      transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
      transforms.outbox.table.field.event.id: id
      transforms.outbox.table.field.event.key: aggregate_id
      transforms.outbox.table.field.event.payload: payload
      transforms.outbox.route.by.field: type
      transforms.outbox.route.topic.replacement: outbox_event.${routedByValue}
      topic.prefix: inventory

logging:
  level:
    root: info
    com.pablords: debug
    org:
      hibernate: ERROR
      springframework:
        orm.jpa: ERROR
        transaction: TRACE
        kafka.transaction: DEBUG

server:
  servlet:
    context-path: /api/v1